services:
  - type: web
    name: eirs-backend
    env: node
    region: oregon
    plan: free
    rootDir: .
    buildCommand: npm install && npm run build
    startCommand: node api/index.js
    envVars:
      - key: MONGO_URL
        scope: build,runtime
        value: mongodb+srv://rijusarkar9640:hgtWfu3E5SqFxZXh@cluster0.6bdcvde.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        value: Secret
      - key: NODE_ENV
        value: production
      - key: RAZORPAY_KEY_ID
        scope: build,runtime
        value: rzp_test_1DP5mmOlF5G5ag
      - key: RAZORPAY_KEY_SECRET
        scope: build,runtime
        value: eGe8jSqnAFZPBFb1Goz3BQGM
